var doers = [
    // Talent
    'Artists',
    'Makers',
    'Tinkerers',
    'Builders',
    'Teachers',
    'Travellers',
    'Photographers',
    'Musicians',
    'Farmers',
    'Filmmakers',
    'Cooks',
    'Actors',
    'Philosophers',
    'Writers',
    'Acrobats',
    'Contortionists',
    'Dancers',
    'Painters',
    'Ceramic Artists',
    'Poets',
    'Ballerinas',
    'Programmers',
    'Scientists',
    'Astronomers',
    'Mechanics',
    'Entrepreneurs',
    'Surfers',
    'Beauticians',
    'Calligraphers',
    'Game Designers',
    'Designers',
    'Equestrians',
    'Outdoor Lovers',
    'Woodworkers',
    'Animators',
    '3D Modellers',
    'Location Scouts',
    'Models',
    'Geologists',
    'Deep Sea Divers',
    'Meteorologists',
    'Aviators',
    'Composers',
    'Vikings',
    'Folly Artists',
    'Concept Artists',
    'Exotics',
    'Creatives',
    'Economists',
    'Singers',
    'Voice Actors',
    'Choreographers',
    'Experience Designers',
    'Interior Designers',
    'Hair Stylists',
    'Body Advocates',
    'Architects',
    'Cartographers',
    'Chemists',
    'Engineers',
    'Fashion Designers',
    'Stargazers',
    'Community Builders',
    'Lighting Designers',
    'Pixies',
    'Fairies',
    'Mermaids',
    'Athletes',
    'Thinkers',
    'Performers',
    'Leaders',
    'Flight Attendants',
    'Truck Drivers',
    'Au Pairs',
    'Archaeologists',
    'Body Builders',
    'Pixel Artists',
    'Researchers',
    'UX Designers',
    'Game Level Designers',
    'App Developers',
    'Data Scientists',
    'Pilots',
    'Pianists',
    'Violinists',
    'Cellists',
    'Illusionists',
    'Illustrators',
    'Flutists',
    'Thereminists',
    'Guitarists',
    'Drummers',
    'Zookeepers',
    'Optimizers',
    'Miners',
    'Gold Diggers',
    'Developers',
    'Scene Designers',
    'Social Artists',
    'Social Designers',
    'Chess Players',
    'Lawyers',
    'Doctors',
    'Nurses',
    'Florists',
    'Chefs',
    'Team Builders',
    'Crafters',
    'Perfume Designers',
    'Bounty Hunters',
    'Pattern Makers',
    'Textile Designers',
    'Makeup Artists',
    'Set Designers',
    'Seamstresses',
    'Astronauts',
    'Gymnasts',
    'German Wheel Girls',
    'Seafarers',
    'Captains',
    'Vocalists',
    'Beatboxers',
    'Anthropologists',
    'Anatomists',
    'Physiologists',
    'Rangers',
    'Salespeople',
    'Oil Painters',
    'Acrylic Painters',
    'Argonauts',
    'Trail Guides',
    'Experimenters',
    'Script Writers',
    'Park Rangers',
    'Submarine Crews',
    'Factory Workers',
    'Packaging Experts',
    'Office Managers',
    'Cosmetologists',
    'Movers',
    'Detail Cleaners',
    'Dentists',
    'Watchmakers',
    'Artwork Restorers',
    'Gardeners',
    'Children Book Authors',
    'Organizers',
    'Story Writers',
    'Marketers',
    'Bus Drivers',
    'Waitresses',
    'City Planners',
    'Tailors',
    'Camera Crews',
    'Editors',
    'Stuntmen',
    'Event Coordinators',
    'Museum Designers',
    'Veterinarians',
    'Furniture Makers',
    'Mathematicians',
    'DIY',
    'Harpists',
    'Automotive Designers',
    'Radiologists',
    'Carpenters',
    'Cargo Ship Crews',
    'Jungle Conservationists',
    'Escape Artists',
    'Character Designers',
    'Babysitters',
    'Bloggers',
    'Vloggers',
    'YouTubers',
    'Marine Biologists',
    'Googlers',
    'Spelunkers',
    'Linguists',
    'Prospectors',
    'Surveyors',
    'Automation Engineers',
    'Lyft Drivers',
    'Doormen',
    'Firefighters',
    'Tree Huggers',
    'Bartenders',
    'Store Clerks',
    'Tile Floor Installers',
    'Tutorial Writers',
    'Documentation Writers',
    'Smoothie Mixers',

    'Blender Artists',
    'Linux Users',
    'MyPaint Users',

    // Interests
    'Tandoori Rice Lovers',
    'Cat Lovers',
    'Animal Lovers',
    'Nature Lovers',
    'Dog Lovers',
    'Good Food Lovers',
    'Technology Enthusiasts',
    'Spaceship Owners',
    'Intergalactic Travellers',
    'Beach Frisbee Nudists',
    'Career Adventurers',
    'Yoga',
    'Climbers',
    'Ninjas',
    'Risk Takers',
    'Jazz',
    'Raccoon Lovers',

    // People
    'People',
    'Adventurers',
    'Bird Lovers',
    'Sisters',
    'Betty Boop Lovers',
    'Heroes',
    'Shoemakers',
    'Heroines',
    'Sweat!',
    'Trailblazers',
    'Herpetologists',
    'Students',
    'Wildlife Photographers',
    'Cookies',
    'Brainstorming',
    'Spaceport Directors',
    'Decision Making',
    'Thrill Seekers',
    'Stellar Health',
    'Lifestyle Designers',

    // Abstracts
    'Doers',
    'Go Getters',
    'Purpose',
    'Spontaneity',
    'Upgrading',
    'Idea Solidification',
    'Making Sense',
    'New Heights',
    'Rejuvenation',
    'Retrospection',
    'Spirituality',
    'Dazzles',
    'Introspection',
    'Morning Debriefs',
    'Eclecticism',
    'Passionates',
    'Absolute Mastery',
    'Sensuality',
    'Advice',
    'Playfulness',
    'Waltzing',
    'Assimilation',
    'Unboxing',
    'Search',
    'Compliments',
    'Sweetness',
    'Namaste',
    'Blooming',
    'Implementation',
    'Adoration',
    'Chaos',
    'Connection',
    'Delights',
    'Thoughtfulness',
    'Today',
    'Attractiveness',
    'Meaning',
    'Specialness',
    'Loveliness',
    'Experience',
    'Experiences',
    'Sexiness',
    'Sweets',
    'Endurance',
    'Perseverance',
    'Learning',
    'Moments',
    'Collaboration',
    'Entertainment',
    'Culture',
    'Fine Etiquette',
    'Ideas',
    'Joy',
    'Creativity',
    'Production',
    'DJs',
    'Glamour',
    'Discovery',
    'Progress',
    'Beauty',
    'Brightness',
    'Introspection',
    'Introductions',
    'Great Energy',
    'Newness',
    'Flowering',
    'Color',
    'Freshness',
    'Uniqueness',
    'Language',
    'Expression',
    'Desire',
    'Glory',
    'Epics',
    'Human Epics',
    'Mystery',
    'Dazzles',
    'Excitement',
    'Concepts',
    'Charm',
    'Strategy',
    'Performance',
    'Passion',
    'Cuteness',
    'Unknowns',
    'Surprises!',
    'Fascination',
    'Emotion',
    'Exuberance',
    'Love',
    'Magic',
    'Fantasy',
    'Personality',
    'Adventure',
    'Little Things',
    'Big Things',
    'Independence',
    'Senses',
    'Analysis',
    'Exploration',
    'Abundance',
    'Opportunity',
    'Endless Possibilities',
    'Amazement',
    'Curiosity',
    'Acceleration',
    'Inspiration',
    'Logic',
    'Understanding',
    'Balance',
    'Intel',
    'Eventfulness',
    'Beautification',
    'Know How',
    'Knowledge',
    'Awesome',
    'Character',
    'Laughter',
    'Soul',
    'Feeling',
    'Interaction',
    'Humanness',
    'Action!',

    // Quotes
    '"Yes"',
    '"Welcome!"',
    '"Muahahaha!"',
    '"Aha!"',
    '"Let\'s do this!"',
    '"Let\'s figure it out!"',

    // ???
    '???',

    // Places
    'Campouts',
    'Campfire Chats',
    'Home',
    'Cities',
    'Neighborhoods',
    'Towns',
    'Villages',
    'Communities',
    'Planet Earth',
    'Parties',
    'Everyday',
    'Pizza',
];

function change(looper, id, what) {
    var last = -1;

    var randInt = function (min, max) {
        return Math.floor(Math.random() * (max - min + 1)) + min;
    }

    var nextInt = function (min, max) {
        var current = last;

        while(last === current) {
            last = randInt(min, max);
        }

        return last;
    }

    var loop = function () {
        var color = 'hsl(' + randInt(0, 359) + ', 90%, 50%)';

            var text = $('<span>').text(what[nextInt(0, what.length - 1)]);

            $('#' + id).empty().append(text);

            text.css({color: color, 'text-shadow': '2px 2px 4px black, 0 0 1rem ' + color})
                .textillate({
                    minDisplayTime: 1000,
                    in: { effect: 'bounceInDown', reverse: false, delay: 20, shuffle: true},
                    out: { effect: 'bounceOutUp', reverse: false, delay: 20, shuffle: true, callback: function () { looper.loop(); } },
                    loop: true
                });
    }

    loop();

    return loop;
}

function loop() {
    var readyCount = 0;

    var a = [
        change(this, 'doers', doers),
    ];

    var loop = function () {
        if (readyCount < a.length) {
            readyCount++;
            return;
        }

        var readyCount = 0;

        for(var b in a) {
            if (!a.hasOwnProperty(b)) continue;

            b();
        }
    };

}

$(function () {
    loop();
});